### ISSUE TITLE
无法启用，报错。

### ISSUE THREAD

**Issue by AozoraWings** [XGHeaven/minecraft-manager#2]
[root@localhost mcapijs]# minecraft-manager --api 25618 -d /MInecraft/mcapi
/usr/lib/node_modules/minecraft-manager/node_modules/koa-bodyparser/index.js:72
  return async function bodyParser(ctx, next) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/minecraft-manager/dist/api/index.js:61:22)

**Comment by XGHeaven** [comment]
请使用 6.7 以上版本的 node
